Added django-receiver-on-top codemod
pixee/codemodder-python pull request #153
Opened 2023-11-29 13:15 UTC by andrecsilva

## Overview
Added a codemod that puts `@receiver` decorator on top.

2023-11-29 14:32 UTC, drdavella requested changes
Looks really nice overall. Just relatively minor changes requested.

2023-11-29 14:32 UTC, drdavella commented on tests/codemods/test_django_receiver_on_top.py
> +class TestDjangoReceiverOnTop(BaseCodemodTest):
It would be good to have a test case with a different `receiver` import where no change is made.

2023-11-29 14:32 UTC, drdavella commented on src/core_codemods/docs/pixee_python_django-receiver-on-top.md
> +Django uses signals to notify and handle actions that happens elsewhere in the application. You can define a response to a given signal by decorating a function with the `@receiver(signal)` decorator
This is a nice description. I actually learned something.

2023-11-29 14:33 UTC, drdavella commented on src/core_codemods/django_receiver_on_top.py
> +    SUMMARY = "Ensures @receiver is on top of all decorators"
```suggestion
    SUMMARY = "Ensure Django @receiver is the first decorator"
```

2023-11-29 14:58 UTC, clavedeluna approved these changes

2023-11-29 18:02 UTC, drdavella requested changes

2023-11-29 18:02 UTC, drdavella commented on tests/codemods/test_django_receiver_on_top.py
> +        @receiver(request_finished)
Sorry for the nitpick but for this test case `@receiver` should really be the second decorator and the order should not be modified.

2023-11-30 11:18 UTC, andrecsilva commented on tests/codemods/test_django_receiver_on_top.py
> +        @receiver(request_finished)
Yeah, my bad. Typical copy-paste mistake.

2023-11-30 14:37 UTC, drdavella approved these changes

2023-11-30 19:15 UTC, merged