New codemod: `use-set-literal`
pixee/codemodder-python pull request #192
Opened 2023-12-22 21:18 UTC by drdavella

## Overview
*A simple codemod that simplifies set literals*

2023-12-26 21:39 UTC, clavedeluna commented on src/core_codemods/use_set_literal.py
> +                            self.add_change(original_node, self.CHANGE_DESCRIPTION)
can move this line to line 20 so it doesn't get called twice

2023-12-26 21:40 UTC, clavedeluna commented on src/core_codemods/use_set_literal.py
> +                                self.add_change(original_node, self.CHANGE_DESCRIPTION)
should also be able to call `self.report_change(original_node)` which I think is nicer but they're kinda dupes of each other

2023-12-26 21:40 UTC, clavedeluna commented on tests/codemods/test_use_set_literal.py
> +
worth adding `assert len(self.file_context.codemod_changes) == 1` (or 0) to each test case

2024-01-02 10:30 UTC, andrecsilva requested changes

2024-01-02 10:30 UTC, andrecsilva commented on src/core_codemods/use_set_literal.py
> +    def leave_Call(self, original_node: cst.Call, updated_node: cst.Call):
It's lacking the line include/excludes check.

2024-01-03 10:25 UTC, andrecsilva approved these changes

2024-01-03 15:13 UTC, merged