Codemod: parameterization of file path in Flask's send-file
pixee/codemodder-python pull request #214
Opened 2024-01-16 10:27 UTC by andrecsilva

## Overview
* A new codemod that parameterizes paths given as input to Flask `send-file` function.
* Adds some functionality to generate available names in a given scope.

2024-01-16 15:51 UTC, clavedeluna commented
Does sonarcloud provide in-file or settings to let it know we expect insecure code in samples?

2024-01-16 15:59 UTC, drdavella approved these changes
This is a nice codemod. Just a few small requests for metadata updates before merging.

2024-01-16 15:59 UTC, drdavella commented on src/core_codemods/docs/pixee_python_flask-send-file-path-parameterization.md
> +In a path injection attack, the malicious agent can craft a path containing special paths like `./` or `../` to resolve an unintended file. This allows the agent to overwrite, delete or read arbitrar
```suggestion
In a path traversal attack, the malicious agent can craft a path containing special paths like `./` or `../` to resolve a file outside of the expected directory path. This potentially allows the agent to overwrite, delete or read arbitrary files. In the case of `flask.send_file`, the result is that a malicious user could potentially download sensitive files that exist on the filesystem where the application is being hosted.
```

2024-01-16 15:59 UTC, drdavella commented on src/core_codemods/docs/pixee_python_flask-send-file-path-parameterization.md
> +The `send_file` function from Flask is susceptible to a path injection attack if its input is not proper validated.
```suggestion
The `send_file` function from Flask is susceptible to a path traversal attack if its input is not proper validated. 
```

2024-01-16 15:59 UTC, drdavella commented on src/core_codemods/flask_send_file_path_parameterization.py
> +    SUMMARY = "Replaces `send_file` with `send_from_directory`"
```suggestion
    SUMMARY = "Replace unsafe usage of `flask.send_file`"
```

2024-01-16 16:04 UTC, clavedeluna requested changes

2024-01-16 16:04 UTC, clavedeluna commented on src/core_codemods/docs/pixee_python_flask-send-file-path-parameterization.md
> +The `send_file` function from Flask is susceptible to a path injection attack if its input is not proper validated.
```suggestion
The `Flask` `send_file` function is susceptible to a path injection attack if its input is not properly validated. 
```

2024-01-16 16:04 UTC, clavedeluna commented on src/core_codemods/flask_send_file_path_parameterization.py
> +    NAME = "flask-send-file-path-parameterization"
I maybe would've called it `replace-flask-send-file` or something without the word parametrization, but maybe Dan has stronger opinions

2024-01-16 16:04 UTC, clavedeluna commented on src/core_codemods/flask_send_file_path_parameterization.py
> +    SUMMARY = "Replaces `send_file` with `send_from_directory`"
I'd add `Flask` somewhere in the summary / description

2024-01-16 16:04 UTC, clavedeluna commented on tests/codemods/test_flask_send_file_path_parameterization.py
> +from textwrap import dedent
can remove dedent use and rely on BaseCodemodTest doing it

2024-01-16 16:04 UTC, clavedeluna commented on tests/codemods/test_flask_send_file_path_parameterization.py
> +        assert len(self.file_context.codemod_changes) == 0
not seeing a basic param of just a string without interpolation, like `send_file('path')`

2024-01-16 16:04 UTC, clavedeluna commented on tests/samples/flask_send_file_path_parameterization.py
> +    return send_file(f'path/to/{name}.txt')
ah I guess you can just dismiss it to say it's tests

2024-01-16 18:06 UTC, drdavella commented on src/core_codemods/flask_send_file_path_parameterization.py
> +    NAME = "flask-send-file-path-parameterization"
I like your shorter suggestion.

2024-01-17 11:02 UTC, andrecsilva commented on src/core_codemods/flask_send_file_path_parameterization.py
> +    NAME = "flask-send-file-path-parameterization"
Next in my wishlist: a codemod that renames a codemod in `codemodder-python`.

2024-01-17 14:23 UTC, clavedeluna approved these changes

2024-01-17 17:47 UTC, merged