Codemod `fix-assert-tuple`
pixee/codemodder-python pull request #217
Opened 2024-01-18 18:53 UTC by clavedeluna

## Overview
*One sentence, high-level explanation of WHY changes are introduced and/or business need*

## Description

* What/WHY/how these changes are needed

## Additional Details
* Any follow up tickets or discussion
* Any specific merge / deploy details

2024-01-19 13:11 UTC, andrecsilva approved these changes

2024-01-19 13:11 UTC, andrecsilva commented on src/core_codemods/fix_assert_tuple.py
> +                        return updated_node
Suggestion:
```python
match updated_node.body:
    case [cst.Assert(test=cst.Tuple(elements = [head, *_]))]:
        ...
```

2024-01-19 13:11 UTC, andrecsilva commented on src/core_codemods/docs/pixee_python_fix-assert-tuple.md
> +
I feel those empty lines shouldn't be here.

2024-01-22 14:41 UTC, drdavella requested changes
Very nice overall but some suggestions for metadata

2024-01-22 14:41 UTC, drdavella commented on src/core_codemods/fix_assert_tuple.py
> +        summary="Fix Assert on Populated Tuple",
Suggestion:
```suggestion
        summary="Fix `assert` on Non-Empty Tuple Literal",
```

2024-01-22 14:41 UTC, drdavella commented on src/core_codemods/fix_assert_tuple.py
> +        "Separate assertion on a populated tuple into multiple assert statements."
```suggestion
        "Separate assertion on a non-empty tuple literal into multiple assert statements."
```

2024-01-22 14:41 UTC, drdavella commented on src/core_codemods/docs/pixee_python_fix-assert-tuple.md
> +An assertion on a non-empty tuple will always evaluate to `True` so it's likely to be written unintentionally. This codemod will write one assert statement for each item in the tuple.
```suggestion
An assertion on a non-empty tuple will always evaluate to `True`. This means that `assert` statements involving non-empty tuple literals are likely unintentional and should be rewritten. This codemod rewrites the original `assert` statement by creating a new `assert` for each item in the original tuple.
```

2024-01-22 14:41 UTC, drdavella commented on src/core_codemods/fix_assert_tuple.py
> +        review_guidance=ReviewGuidance.MERGE_WITHOUT_REVIEW,
I think this should be `MERGE_AFTER_CURSORY_REVIEW` because there's a decent change we break some tests.

2024-01-23 11:11 UTC, clavedeluna commented on src/core_codemods/fix_assert_tuple.py
> +                        return updated_node
I personally don't prefer this version

2024-01-23 20:40 UTC, drdavella approved these changes

2024-01-24 14:54 UTC, merged