Django models `__str__` codemod
pixee/codemodder-python pull request #302
Opened 2024-02-25 18:49 UTC by clavedeluna

## Overview
*One sentence, high-level explanation of WHY changes are introduced and/or business need*

## Description

* What/WHY/how these changes are needed

## Additional Details
* Any follow up tickets or discussion
* Any specific merge / deploy details

Closes #287

2024-02-27 12:49 UTC, andrecsilva approved these changes
Minor change

2024-02-27 12:49 UTC, andrecsilva commented on src/core_codemods/django_model_without_dunder_str.py
> +                'fields_str = ", ".join([f"{field.name}={getattr(self, field.name)}" for field in self._meta.fields])'
Change this from a list to a generator (`join([...])` -> `join((...))`).

2024-02-27 12:49 UTC, andrecsilva commented on src/core_codemods/docs/pixee_python_django-model-without-dunder-str.md
> ++        fields_str = ", ".join([f"{field.name}={getattr(self, field.name)}" for field in self._meta.fields])
Change this example to reflect the change in the other comment.

2024-02-27 13:06 UTC, clavedeluna commented on src/core_codemods/django_model_without_dunder_str.py
> +                'fields_str = ", ".join([f"{field.name}={getattr(self, field.name)}" for field in self._meta.fields])'
doh! 🤦

2024-02-27 15:08 UTC, drdavella requested changes
Looks really nice overall. Just some requests for updating metadata and then we should be good.

2024-02-27 15:08 UTC, drdavella commented on src/core_codemods/docs/pixee_python_django-model-without-dunder-str.md
> +Without this change, the `Question` objects look like this in the interactive Django shell:
```suggestion
Without this change, the  string representation of `Question` objects look like this in the interactive Django shell:
```

2024-02-27 15:08 UTC, drdavella commented on src/core_codemods/docs/pixee_python_django-model-without-dunder-str.md
> +If you've ever actively developed or debugged a Django application, you may have noticed Django models and their instances can sometimes be hard to read or distinguish one instance from another. Load
```suggestion
If you've ever actively developed or debugged a Django application, you may have noticed that the string representations of Django models and their instances can sometimes be hard to read or to distinguish from one another. Loading models in the interactive Django console or viewing them in the admin interface can be puzzling. This is because the default string representation of Django models is fairly generic.
```

2024-02-27 15:08 UTC, drdavella commented on src/core_codemods/docs/pixee_python_django-model-without-dunder-str.md
> +We've written this codemod to make your model objects human-readable. It will automatically detect all of your model's fields and display them as a nice string.
```suggestion
This codemod is intended to make the string representation of your model objects more human-readable. It will automatically detect all of your model's fields and display them as a descriptive string.
```

2024-02-27 15:08 UTC, drdavella commented on src/core_codemods/docs/pixee_python_django-model-without-dunder-str.md
> +For example, the `Question` model from Django's popular Poll App tutorial will look like this:
```suggestion
For example, the default string representation of the `Question` model from Django's popular Poll App tutorial looks like this:
```

2024-02-27 15:08 UTC, drdavella commented on src/core_codemods/django_model_without_dunder_str.py
> +        name="django-model-without-dunder-str",
Not a huge deal but I feel like we're sometimes inconsistent as to whether a codemod is phrased in terms of a problem or a fix. I think we should prefer names in terms of fixes `add-django-model-dunder-str` but maybe we can just take it as a suggestion going forward.

2024-02-27 15:08 UTC, drdavella commented on src/core_codemods/django_model_without_dunder_str.py
> +        summary="Ensure Django Model Classes Implement A `__str__` Method",
```suggestion
        summary="Ensure Django Model Classes Implement a `__str__` Method",
```

2024-02-28 16:13 UTC, drdavella approved these changes

2024-02-28 16:34 UTC, merged