Adds support for format operators in SQLQueryParameterization
pixee/codemodder-python pull request #361
Opened 2024-03-12 13:57 UTC by andrecsilva

## Overview
SQLQueryParameterization will now parameterize queries built with the format operator `%`

2024-03-12 18:58 UTC, clavedeluna requested changes

2024-03-12 18:58 UTC, clavedeluna commented on src/codemodder/codemods/transformations/remove_empty_string_concatenation.py
> +def _is_empty_string_literal(node):
same function as the other file so move to a utility module and remove the leading `_` since it won't be private

2024-03-12 18:58 UTC, clavedeluna commented on src/codemodder/utils/linearize_string_expression.py
> +        # TODO try to resolve this
this todo doesn't make a lot of sense without more context, maybe remove it?

2024-03-12 18:58 UTC, clavedeluna commented on src/core_codemods/sql_parameterization.py
> +        return prefix, raw_value
maybe I'm missing something super subtle but can't you just
```suggestion
prefix = self.extract_prefix(node))
return prefix, raw_value
```
no if check, no double return

2024-03-12 18:58 UTC, clavedeluna commented on src/core_codemods/sql_parameterization.py
> +                        + "'"
probably cleaner to make it an f-str instead of using +

2024-03-13 13:40 UTC, drdavella approved these changes
This looks great overall. It's a lot of very impressive work, thanks for the effort. 

I'm starting to see how some of these pieces could be taken and reused for other kinds of codemods (e.g. xpath injection).

2024-03-13 13:40 UTC, drdavella commented on src/codemodder/utils/format_string_parser.py
> +def parse_formatted_string(
This is pretty heroic, nice work. I could have sworn that there was something in the standard library that helped to tokenize format strings but I'm having trouble digging it up right now.

2024-03-13 13:40 UTC, drdavella commented on src/core_codemods/sql_parameterization.py
> +        # (1) FindQueryCalls -> (2) ExtractParameters -> (3) SQLQueryParameterization
Just a nitpick but this should probably be a docstring instead of a comment.

2024-03-13 13:56 UTC, clavedeluna approved these changes

2024-03-14 15:22 UTC, merged