Implement "sugar" API for SecureRandom codemod example
pixee/codemodder-python pull request #5
Opened 2023-08-25 01:43 UTC by drdavella

## Overview
*Implement API to provide a cleaner example for our `SecureRandom` codemod*

## Description

* We need to implement a simpler API for creating custom (and internal) codemods
* This is a highly visible part of our product. It's in our docs and it comes up in demos and talks
* I tried to emulate the simplicity of the Java codemodder example for the same rule
* I worked backwards by writing the codemod the way that I would want to implement it
* Next I wrote some code to actually implement the API
  * I was able to do this without making any major changes to the existing codemodder API
  * I'm not entirely proud of the solution. It's not really general at all and there is a lot of metaprogramming glue to hack it all together
  * However, it serves its purpose and gives us a cleaner working example for this rule
* We are going to need to iterate on the API itself and also on the underlying implementation
* I also think there are many opportunities for improvement in the existing codemod API itself. Making some of these changes might help facilitate a cleaner solution all around
  * I think I'm not a big fan of the use of class-level attributes, but I need to think about a better solution
  * I'm also a little wary of the helper/mixin pattern, although that's hard to avoid too
  * Some of this was clearly driven by the design of libCST itself, which dictates the form of our solutions to some extent
  * However we should think outside the box and consider whether there might be other ways to phrase these codemods, even outside the context of classes
* I'm looking for feedback both on the final result itself but also on other ways forward

2023-08-25 01:50 UTC, drdavella commented
Linter rules are failing at the moment but I'm not expecting to merge this in the immediate future so I will fix it a little later.

2023-08-25 01:51 UTC, drdavella commented on codemodder/codemods/secure_random.py
Your review should start in this file. This is the end result that we are going for, and all of the other changes facilitate this API.

2023-08-25 02:08 UTC, nahsra commented on codemodder/codemods/secure_random.py
This is so much more beautiful 👨‍🍳 💋

2023-08-25 10:41 UTC, clavedeluna commented
> I think I'm not a big fan of the use of class-level attributes, but I need to think about a better solution

I can at least explain the **why** here. It's purely to store state for codemodder runs. So when codemodder runs, We want to store all results for the same codemod for that codemod. The most "natural" OOP   way to do that was as a class attr, but as you've seen us discuss this, it's not great. Given the why, choosing some data storage / state keeping mechanism that works for codemodder would be the goal.

2023-08-25 10:50 UTC, clavedeluna commented on codemodder/api/__init__.py
> +    class cls(has_yaml, orig, SemgrepCodemod, BaseTransformer, Helpers):
just puuurely to avoid confusion, could you rename it to `klas`?

2023-08-25 10:50 UTC, clavedeluna commented on codemodder/api/__init__.py
> +        CHANGE_DESCRIPTION = metadata.DESCRIPTION
yeah we still haven't made a distinction between the overall codemod description versus each little change's description. fine for now

2023-08-25 10:50 UTC, clavedeluna commented on codemodder/codemods/semgrep/secure_random.yaml
> +        ...
are you able to entirely remove this file now?

2023-08-25 10:51 UTC, clavedeluna commented
things I love
- including the yaml directly in the rule instead of creating our own semgrep yaml file. why didn't we do this before!!! Yay Dan!

concerns
- as you probably saw when implementing this, specifically `leave_Call`, each rule is so subtly differet depending on what we're changing. while I love the API `self.update_call_target(target_node, "secrets.SecureRandom()")`, I'm not sure how generalizable it will be. But I'm on board to start this API and let it inform us and "force" us to generalize. The way we've been operating now is "just write rules, generalize later", but with the new direction coming out of the onsite, it seems like we need to flip that MO. I'm fine with that!

2023-08-25 12:00 UTC, andrecsilva requested changes
To put it bluntly: I don't like it. I can see something like this being used for a alternative for writing simple codemods, but I feel it will crumble with anything that is more complex than replacing a single call. Of course, this is only a problem if you're enforcing this particular standard to all codemods.

The only required change is the one pointed by the comment attached to `on_result_found`. The rest are opinions/suggestions/future work and may be promptly ignored.

2023-08-25 12:00 UTC, andrecsilva commented on codemodder/api/helpers.py
> +        # TODO: do we need to check if this import already exists?
`AddImportsVisitor` already checks that.

2023-08-25 12:00 UTC, andrecsilva commented on codemodder/api/helpers.py
> +        AddImportsVisitor.add_needed_import(self.context, import_name)
I've recently discovered that `AddImportsVisitor` will not work well if the file has imports outside of the "header".
Try this example:
```python
import random
random.random()

import os
```
It will produce:
```python
secrets.SystemRandom().random()

import os
import secrets
```

2023-08-25 12:00 UTC, andrecsilva commented on codemodder/api/__init__.py
> +    class cls(has_yaml, orig, SemgrepCodemod, BaseTransformer, Helpers):
Locking this to `BaseTransformer` will make us unable to use other transformations before and after it. 

For reference, check the `UrlSandbox` and `RemoveUnusedImports` codemods for example of codemods that are not simple transformers.

2023-08-25 12:00 UTC, andrecsilva commented on codemodder/codemods/secure_random.py
> +@codemod(
Probably the hottest take on this review, but this smells like Java code. Using multiple inheritance to enforce standards on a class is not only more explicit but it would be more natural in python.

My understanding is that usual use case of decorators is to "enhance" something without changing its implementation (directly at least). Here we are not only using a decorator to enforce patterns/standards on the class, but at first glance it looks like a decorator that only adds metadata.

2023-08-25 12:00 UTC, andrecsilva commented on codemodder/codemods/secure_random.py
> +    def on_result_found(self, original_node):
Ever wondered why the  `leave_*` methods have two parameters for a node (`original_node` and `updated_node`)?

If you make changes to a child node of `original_node`, `original_node` won't contain that change, but `updated_node` will. So making changes directly to `original_node` here will erase any previous changes to its children.

The official docs recommends to always make changes to `updated_node`:
https://libcst.readthedocs.io/en/latest/visitors.html#libcst.CSTTransformer

2023-08-25 12:16 UTC, nahsra commented
> Of course, this is only a problem if you're enforcing this particular standard to all codemods.

I think this is the key part. Simple things should be simple, and complex things should be possible. We should name the codemod subtype according to the narrow pattern is it intended to support.

2023-08-25 12:23 UTC, clavedeluna commented on codemodder/api/__init__.py
another idea I thought. The long term goal is to separate the codemodder repo (the thing that runs codemods, the engine) from codemods and codemod writing. So I think this new api dir should go under the codemods directory.

2023-08-25 13:03 UTC, drdavella commented on codemodder/codemods/semgrep/secure_random.yaml
> +        ...
Yes it's not being used anymore but I kept it around for posterity. I'll remove it once we decide to go with this implementation.

2023-08-25 13:06 UTC, drdavella commented on codemodder/codemods/secure_random.py
> +@codemod(
I don't have a particular commitment to using the decorator, although I do think it enabled the kind of metaprogramming that I wanted to do here. But I'd be okay with rephrasing this in terms of inheritance.

2023-08-25 13:10 UTC, drdavella commented on codemodder/codemods/secure_random.py
> +    def on_result_found(self, original_node):
Thanks, this is a good call-out. I will fix it.

2023-08-25 16:49 UTC, drdavella commented
> > I think I'm not a big fan of the use of class-level attributes, but I need to think about a better solution
> 
> I can at least explain the **why** here. It's purely to store state for codemodder runs. So when codemodder runs, We want to store all results for the same codemod for that codemod. The most "natural" OOP way to do that was as a class attr, but as you've seen us discuss this, it's not great. Given the why, choosing some data storage / state keeping mechanism that works for codemodder would be the goal.

Thanks for the explanation. Could we create some kind of simple data store (could even be a dict as first pass) and inject it into each codemod class using the context? It feels like this data should be centralized somehow instead of stored on each individual codemod.

2023-08-25 16:50 UTC, drdavella commented on codemodder/api/__init__.py
> +    class cls(has_yaml, orig, SemgrepCodemod, BaseTransformer, Helpers):
That's fair. Let's just consider this a first-pass right now and we can revisit.

2023-08-25 16:50 UTC, drdavella commented on codemodder/api/helpers.py
> +        AddImportsVisitor.add_needed_import(self.context, import_name)
@andrecsilva this feels like something that needs to be fixed separately, correct?

2023-08-25 16:55 UTC, drdavella commented
> To put it bluntly: I don't like it. I can see something like this being used for a alternative for writing simple codemods, but I feel it will crumble with anything that is more complex than replacing a single call. Of course, this is only a problem if you're enforcing this particular standard to all codemods.

@andrecsilva I appreciate your honesty. You are right that it is very brittle as implemented. However, I think we should begin by looking at the very simplest codemods and figuring out the cleanest/clearest way to express those. It's possible that we already have another codemod or two that could be expressed simply in this way (maybe with a few additional helper methods) and I think we should push on those a bit while we iterate on the design.

Also, just to be clear, I also think there should always be a "hard" way to write these that is more expressive and more powerful. Many of our own codemods will need to be written using a more powerful API. But we want to make the easy cases easy.

2023-08-25 16:57 UTC, drdavella commented
The fact that we have these kinds of linter errors (and we have already suppressed some of them elsewhere) suggests to me that we could improve the design somehow. I think this is part of what makes me a little suspicious of mixins.
```
Using config file /home/runner/work/codemodder-python/codemodder-python/pylintrc
************* Module codemodder.codemods.secure_random
codemodder/codemods/secure_random.py:23:8: E1101: Instance of 'SecureRandom' has no 'add_needed_import' member (no-member)
codemodder/codemods/secure_random.py:24:15: E1101: Instance of 'SecureRandom' has no 'update_call_target' member (no-member)
************* Module codemodder.api.helpers
codemodder/api/helpers.py:10:44: E1101: Instance of 'Helpers' has no 'context' member (no-member)
************* Module codemodder.api
codemodder/api/__init__.py:86:31: E1102: attr is not callable (not-callable)
************* Module tests.codemods.test_secure_random
tests/codemods/test_secure_random.py:10:[15](https://github.com/pixee/codemodder-python/actions/runs/5970870880/job/16199112807?pr=5#step:6:16): E1101: Class 'SecureRandom' has no 'RULE_IDS' member (no-member)
************* Module integration_tests.test_secure_random
integration_tests/test_secure_random.py:[22](https://github.com/pixee/codemodder-python/actions/runs/5970870880/job/16199112807?pr=5#step:6:23):25: E1101: Class 'SecureRandom' has no 'CHANGE_DESCRIPTION' member (no-member)
```

2023-08-25 18:04 UTC, andrecsilva commented on codemodder/api/helpers.py
> +        AddImportsVisitor.add_needed_import(self.context, import_name)
Yes, I sorta know how to do it, but this is something that will probably take a few days to implement. I think we are fine for now, it's mostly an edge case.

2023-08-28 01:43 UTC, drdavella commented
I updated this PR to rephrase it in terms of inheritance rather than using a decorator. It required a fairly yucky workaround for the `__init_subclass__` implementations in `SemgrepCodemod` and `BaseTransformer`. 

While I understand the purpose and intent of those `__init_subclass__` methods and the behavior makes good sense to me, I also think that we have uncovered an unintended consequence of doing things that way, and we might want to revisit that implementation. 

The main problem is that `__init_subclass__` makes it practically impossible for anyone else to define a subclass in such a way that the required attributes are defined dynamically. This seems like a reasonable use case to me, and as you can see I had to jump through some hoops to make it work for this (interim) implementation. I think i really want to understand why these things are implemented in terms of attributes that are checked at class definition time rather than attributes and/or properties that are checked later.

Also, just for the record, the API introduced in this PR feels very provisional to me and will require some iteration and redesign over time. But I think it gets us close enough to a simplified example that we can feel comfortable publicizing (cc @nahsra).

2023-08-28 11:03 UTC, clavedeluna commented on codemodder/codemods/api/__init__.py
> +    def __init_subclass__(cls):
I"m glad you can now see why we did this... I think if we go ahead and stop using class level attr and instead use instance vars only, which then leads us to assume that one codemod run will instantiate a codemod only once (ahem, singleton?), then we can remove all of this. Of course right now a codemod gets instantiated multiple times, one time per file in `run_codemods_for_file`.

It's crazy that we can't come up with a clean pattern for "I want a class pattern that will store data across all instances of it". It definitely sounds like a singleton, though I know it isn't our favorite pattern either.

2023-08-28 13:10 UTC, andrecsilva approved these changes
As long as we understand that this is a provisional solution, I'm fine with this.

While it feels hacky, the operating classes are there and it does give a general feeling of how those will be organized.

2023-08-28 13:14 UTC, clavedeluna commented
rebased for you but will let you merge. I can use this branch as a starting point

2023-08-28 15:18 UTC, merged