first semgrep sarif codemod for jinja autoescape
pixee/codemodder-python pull request #687
Opened 2024-07-01 20:51 UTC by clavedeluna

## Overview
*Add support for OSS semgrep codemod for jinja2 autoescape, along with the necessary code to support semgrep codemods in general*

Closes #677

2024-07-02 14:28 UTC, drdavella requested changes
Looks great, only substantive comment is about the codemod ID.

2024-07-02 14:28 UTC, drdavella commented on src/codemodder/codemods/semgrep.py
> -class SemgrepSarifFileDetector(BaseDetector):
It's not a big deal but I think this is a breaking API change. Is there any chance we can keep the import in this module for backwards compability?

2024-07-02 14:28 UTC, drdavella commented on src/core_codemods/semgrep/semgrep_enable_jinja2_autoescape.py
> +    name="enable-jinja2-autoescape-semgrep",
I don't think we need `semgrep` in the codemod name since its encoded by the origin.

2024-07-02 15:20 UTC, clavedeluna commented on src/codemodder/codemods/semgrep.py
> -class SemgrepSarifFileDetector(BaseDetector):
ahh hmm good point, haven't though about backwards compat in a while. I can just put it back, no big deal.

2024-07-02 15:21 UTC, clavedeluna commented on src/core_codemods/semgrep/semgrep_enable_jinja2_autoescape.py
> +    name="enable-jinja2-autoescape-semgrep",
you're right! Since now only core codemods can be requested by name. The Sonar ones have the id in the name which hinted at that when I wrote this.

2024-07-02 15:37 UTC, drdavella reviewed
@clavedeluna I think the new test failure is real since it's asserting on the previous name 😅

2024-07-02 16:22 UTC, clavedeluna commented
@drdavella latest failure actually reminds us that unique codemod names are at least important in docs generation...so need to see how to update that given two same keys

2024-07-03 11:15 UTC, clavedeluna commented
@drdavella sorry for the churn here, this is the first time we have a codemod with the same name as another so it's causing more test failure and questions than I expected. The latest failure suggests something new, which is that we can't register a codemod with the same name as another [here](https://github.com/pixee/codemodder-python/blob/main/src/codemodder/registry.py#L71). It just gets skipped. We have two options here
1. `self._codemods_by_name`  should only ever be used for pixee codemods.
2. fully deprecate `self._codemods_by_name` and only use `self._codemods_by_id` everywhere

Both are easy enough changes I can do it here. LMK what you think works best in terms of customer usability / backward compat. I personally would just go for #2 and nuke the idea of codemod name if we can, to avoid future confusion.

2024-07-03 11:59 UTC, drdavella commented
@clavedeluna I like solution #1 for the short term if it gets us over the hump for this PR. I think we were implicitly doing that anyway (or at least that was my personal assumption). #2 might not be a bad idea to ticket for the longer term.

2024-07-03 14:41 UTC, clavedeluna commented
offline we've agreed to just add -semgrep to the name and work on the options mentioned above in a separate ticket

2024-07-03 14:51 UTC, clavedeluna commented
See https://github.com/pixee/codemodder-python/issues/697

2024-07-03 16:22 UTC, drdavella approved these changes

2024-07-04 11:59 UTC, merged