Refactor test_multiple
pixee/codemodder-python pull request #92
Opened 2023-08-22 14:20 UTC by andrecsilva

## Overview
Refactors test_multiple

## Description

This is an initial attempt at refactoring test_multiple. It is now very modular with heavy use of fixtures.

The test will now generate all the test parameters for every codemod included in `ALL_CODEMODS` automatically. However, those can be overriden for more orthodox codemods via dictionaries.

## Additional Details

I feel like the `run` fixture could be reused for the whole test suit, speeding up all the integration tests.

There is probably a better way to reorganize these by using pytest's parametrize decorator here. Suggestions are welcome.

2023-08-22 15:21 UTC, clavedeluna requested changes

2023-08-22 15:21 UTC, clavedeluna commented on integration_tests/test_multiple.py
> +    # pylint: disable=unused-argument
instead of disabling you can just make `run` be `_`

2023-08-22 15:21 UTC, clavedeluna commented on integration_tests/test_multiple.py
as a longtime python programmer, this test module is difficult to read. It mixes fixture-based testing with class-based testing. Generally fixtures are separate functions, not methods.

I also feel like we've taken a simple test: "we want to test running all default codemods together and asserting all results, to see if one codemod accidentally affects another" into a test that's difficult to reason through. 

Would it be possible to have a fixture-less test instead? Maybe Dan has better suggestions, too.

2023-08-22 15:33 UTC, clavedeluna commented on integration_tests/test_multiple.py
> +    # pylint: disable=unused-argument
oh nvm I think I know why you had to do this. I encountered the same problem with pytest. the arg has to be named

2023-08-22 16:13 UTC, andrecsilva commented on integration_tests/test_multiple.py
The reason for the fixtures is modularity and reuse. Each fixture is pretty atomic and they are cached because of the scope, so they only run once. Some of those should probably be reused with other tests (e.g. run, for codemod specific integration tests).

They are not exactly needed, but I felt that organizing things this way felt more pytest-appropriate.

2023-08-22 16:26 UTC, andrecsilva commented
> Ok so I have an idea. I think the goal here was to prevent us from having to change the indexing in test_multiple.py every time we add a new codemod, bc that's getting super annoying.
> 
> Well, I think a direct solution to that problem is to not use indexing at all. Iff we don't care to assert the order of codemod results (I think we don't...), then we can do:
> 
> ```
> list_of_sample_paths = # create a list of sample.py files
> sorted_results = sorted(results, key=lambda x: x["codemod"])
> for result in sorted_results:
>     assert len(result["changeset"]) == 1 # right now these are all 1 so it's fine
>    assert result["changeset"][0]["path"] in list_of_sample_paths
> 
> # this would ensure that if we add a new codemod it is tested for
> assert len(sorted_results) == len(list_of_sample_paths)
> ```
> 
> or something similar. I can think of a few other tweaks but that's the general idea. What do you think?

If the idea is to check for interference between codemods (that is, adding another codemod won't change the result from another one), then we need some mapping from codemod to expected results.

I feel like doing it as is forgoes this mapping. That is, a codemod could change a file that it should not and this test would still be ok.

One could also say that order of changes is also important, since those affect the final result (my solution does not cover this, but could be easily added).

2023-08-22 16:47 UTC, clavedeluna commented on integration_tests/test_multiple.py
reusable fixtures are typically defined in conftest.py

2023-08-22 16:57 UTC, clavedeluna commented
I'm fine with the mapping. Honestly just moving the fixtures outside of the test class may clean things up enough to make it easier to read.

2023-08-23 11:55 UTC, andrecsilva commented
I'm ditching this solution. I'm not convinced that `test_multiple` is actually doing what is intended in both original and proposed solutions. I'll revisit this later in the future.

2023-08-23 11:55 UTC, closed without merging